### ISSUE TITLE
Adjustable Financial Advisor and Real Estate Agent rates

### ISSUE THREAD

**Issue by ilkeraltin** [ofcyln/mortgage-expense-calculator#52]
I realized that there is no option to adjust rates for Financial Advisor and Real Estate Agent. There are some cases in which that is possible to work with a fixed price or different rates. So it would be great to adjust both of them with the possibility to use a fixed price.

Thanks for the tool, helped a lot!

**Comment by ofcyln** [comment]
Thanks for using the app and your feedback!
I'm adding high priority label to this issue.

**Comment by ofcyln** [comment]
Done

**Comment by ofcyln** [comment]
Done
